/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClassBlock {
  'startTime' : bigint,
  'endTime' : bigint,
  'days' : Array<bigint>,
  'name' : string,
}
export type DateInt = bigint;
export interface RoutineBlock {
  'id' : bigint,
  'startTime' : bigint,
  'endTime' : bigint,
  'blockLabel' : string,
  'category' : string,
}
export interface RoutineBlockInput {
  'startTime' : bigint,
  'endTime' : bigint,
  'blockLabel' : string,
  'category' : string,
}
export type UserId = Principal;
export interface UserProfile { 'sleepTime' : bigint, 'wakeTime' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClasses' : ActorMethod<[UserId], Array<ClassBlock>>,
  'getCompletions' : ActorMethod<[UserId, DateInt], Array<bigint>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getRoutines' : ActorMethod<[UserId], Array<RoutineBlock>>,
  'getUserData' : ActorMethod<
    [UserId],
    {
      'classBlocks' : Array<ClassBlock>,
      'profile' : [] | [UserProfile],
      'routineBlocks' : Array<RoutineBlock>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveClasses' : ActorMethod<[Array<ClassBlock>], undefined>,
  'saveCompletions' : ActorMethod<[DateInt, Array<bigint>], undefined>,
  'saveProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRoutines' : ActorMethod<[Array<RoutineBlockInput>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];