/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'sleepTime' : IDL.Nat,
  'wakeTime' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const ClassBlock = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'days' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
});
export const DateInt = IDL.Nat;
export const RoutineBlock = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'blockLabel' : IDL.Text,
  'category' : IDL.Text,
});
export const RoutineBlockInput = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'blockLabel' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClasses' : IDL.Func([UserId], [IDL.Vec(ClassBlock)], ['query']),
  'getCompletions' : IDL.Func([UserId, DateInt], [IDL.Vec(IDL.Nat)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getRoutines' : IDL.Func([UserId], [IDL.Vec(RoutineBlock)], ['query']),
  'getUserData' : IDL.Func(
      [UserId],
      [
        IDL.Record({
          'classBlocks' : IDL.Vec(ClassBlock),
          'profile' : IDL.Opt(UserProfile),
          'routineBlocks' : IDL.Vec(RoutineBlock),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveClasses' : IDL.Func([IDL.Vec(ClassBlock)], [], []),
  'saveCompletions' : IDL.Func([DateInt, IDL.Vec(IDL.Nat)], [], []),
  'saveProfile' : IDL.Func([UserProfile], [], []),
  'saveRoutines' : IDL.Func([IDL.Vec(RoutineBlockInput)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'sleepTime' : IDL.Nat,
    'wakeTime' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const ClassBlock = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'days' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
  });
  const DateInt = IDL.Nat;
  const RoutineBlock = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'blockLabel' : IDL.Text,
    'category' : IDL.Text,
  });
  const RoutineBlockInput = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'blockLabel' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClasses' : IDL.Func([UserId], [IDL.Vec(ClassBlock)], ['query']),
    'getCompletions' : IDL.Func(
        [UserId, DateInt],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getRoutines' : IDL.Func([UserId], [IDL.Vec(RoutineBlock)], ['query']),
    'getUserData' : IDL.Func(
        [UserId],
        [
          IDL.Record({
            'classBlocks' : IDL.Vec(ClassBlock),
            'profile' : IDL.Opt(UserProfile),
            'routineBlocks' : IDL.Vec(RoutineBlock),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveClasses' : IDL.Func([IDL.Vec(ClassBlock)], [], []),
    'saveCompletions' : IDL.Func([DateInt, IDL.Vec(IDL.Nat)], [], []),
    'saveProfile' : IDL.Func([UserProfile], [], []),
    'saveRoutines' : IDL.Func([IDL.Vec(RoutineBlockInput)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };